# ProjectNIL Local Development Environment
# Usage: podman compose up -d
# Note: Use `podman compose` (native, with space) not `podman-compose` (Python wrapper)

services:
  postgres:
    image: ghcr.io/pgmq/pg18-pgmq:v1.8.0
    container_name: projectnil-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: projectnil
      POSTGRES_USER: projectnil
      POSTGRES_PASSWORD: projectnil
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U projectnil -d projectnil"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Compiler service (polls compilation_jobs, publishes compilation_results)
  # Note: Run migrations first with `podman compose --profile migrate up liquibase`
  compiler:
    build:
      context: ..
      dockerfile: infra/docker/compiler.Dockerfile
    container_name: projectnil-compiler
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGMQ_URL: jdbc:postgresql://postgres:5432/projectnil
      PGMQ_USERNAME: projectnil
      PGMQ_PASSWORD: projectnil
      ASC_BINARY: asc
      COMPILER_TMP_DIR: /app/tmp/compiler
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8081/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    profiles:
      - full

  # Liquibase migration runner
  # Runs migrations and exits
  liquibase:
    image: liquibase/liquibase:4.30
    container_name: projectnil-migrations
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/liquibase/changelog
    command: >
      --search-path=/liquibase/changelog
      --url=jdbc:postgresql://postgres:5432/projectnil
      --username=projectnil
      --password=projectnil
      --changeLogFile=db.changelog-master.yaml
      update

volumes:
  postgres_data:
