:api-url=http://localhost:9080
# health check
GET :api-url/status

#get all functions
GET :api-url/functions

# post a function (happy path)
POST :api-url/functions
Content-Type: application/json

{
    "name": "echo",
    "description": "Returns input unchanged",
    "language": "assemblyscript",
    "source": "export function handle(input: string): string { return input; }"
}

# post a function (invalid language)
POST :api-url/functions
Content-Type: application/json

{
    "name": "echo",
    "description": "Returns input unchanged",
    "language": "not-assemblyscript",
    "source": "export function handle(input: string): string { return input; }"
}

# post a function (insufficient fn-map keys)
POST :api-url/functions
Content-Type: application/json

{
    "name": "echo",
    "source": "export function handle(input: string): string { return input; }"
}

# get compilation status
# fetch anyone id
:fn-id=6f7c095d-a36c-47dc-bacc-76adc96d6d87
GET :api-url/functions/:fn-id


#delete a function
DELETE :api-url/functions/:fn-id

# try fetch again on the same
GET :api-url/functions/:fn-id

#execute
POST :api-url/functions/:fn-id/execute
Content-Type: application/json

{"input": {"message": "Hello, World!"}}

#see all executions
GET :api-url/executions

# see all executions so far for a func
GET :api-url/functions/:fn-id/executions

:exec-id=918c78f0-f50b-4c77-841f-da57e83844bb

#get info on specific exec
GET :api-url/executions/:exec-id
