:api-url=http://localhost:9079

# health check
GET :api-url/status

# post a function
POST :api-url/functions
Content-Type: application/json

{
    "name": "echo",
    "description": "Returns input unchanged",
    "language": "assemblyscript",
    "source": "export function handle(input: string): string { return input; }"
}

# store fn id
:fn-id=a3cf4ef6-52f0-48be-995b-8b4d6b292ecb

# get compilation status
GET :api-url/functions/:fn-id

# poll until status ready

#execute
POST :api-url/functions/:fn-id/execute
Content-Type: application/json

{"input": {"message": "Hello, World!"}}

# see all executions so far for a func
GET :api-url/functions/:fn-id/executions

:exec-id=06eb8217-c26d-4847-ad3f-561a99e02186

#get info on specific exec
GET :api-url/executions/:exec-id
